main: de.warsteiner.ultimatejobs.UltimateJobs
version: SNAPv1
name: UltimateJobs
author: Warsteiner37 
website: ultimate-systems.org
api-version: 1.13
depend: [Vault]
 
commands:  
  Jobs:
    aliases: [job, work]
     